# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'tcxgen_gui_layout.ui'
#
# Created: Tue Mar 19 23:59:24 2013
#      by: PyQt4 UI code generator 4.8.3
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    _fromUtf8 = lambda s: s

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName(_fromUtf8("MainWindow"))
        MainWindow.resize(661, 548)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(MainWindow.sizePolicy().hasHeightForWidth())
        MainWindow.setSizePolicy(sizePolicy)
        self.centralwidget = QtGui.QWidget(MainWindow)
        self.centralwidget.setObjectName(_fromUtf8("centralwidget"))
        self.SameTrackCheckBox = QtGui.QCheckBox(self.centralwidget)
        self.SameTrackCheckBox.setGeometry(QtCore.QRect(30, 70, 171, 22))
        self.SameTrackCheckBox.setChecked(True)
        self.SameTrackCheckBox.setObjectName(_fromUtf8("SameTrackCheckBox"))
        self.line = QtGui.QFrame(self.centralwidget)
        self.line.setGeometry(QtCore.QRect(10, 450, 641, 16))
        self.line.setFrameShape(QtGui.QFrame.HLine)
        self.line.setFrameShadow(QtGui.QFrame.Sunken)
        self.line.setObjectName(_fromUtf8("line"))
        self.AddDayButton = QtGui.QPushButton(self.centralwidget)
        self.AddDayButton.setGeometry(QtCore.QRect(360, 200, 88, 27))
        self.AddDayButton.setObjectName(_fromUtf8("AddDayButton"))
        self.DayToRemoveList = QtGui.QListWidget(self.centralwidget)
        self.DayToRemoveList.setGeometry(QtCore.QRect(130, 200, 111, 201))
        self.DayToRemoveList.setObjectName(_fromUtf8("DayToRemoveList"))
        self.RemoveDateEdit = QtGui.QDateEdit(self.centralwidget)
        self.RemoveDateEdit.setGeometry(QtCore.QRect(250, 200, 110, 27))
        self.RemoveDateEdit.setDate(QtCore.QDate(2000, 1, 1))
        self.RemoveDateEdit.setCalendarPopup(True)
        self.RemoveDateEdit.setObjectName(_fromUtf8("RemoveDateEdit"))
        self.ClearListButton = QtGui.QPushButton(self.centralwidget)
        self.ClearListButton.setGeometry(QtCore.QRect(250, 370, 88, 27))
        self.ClearListButton.setObjectName(_fromUtf8("ClearListButton"))
        self.horizontalLayoutWidget = QtGui.QWidget(self.centralwidget)
        self.horizontalLayoutWidget.setGeometry(QtCore.QRect(10, 470, 641, 51))
        self.horizontalLayoutWidget.setObjectName(_fromUtf8("horizontalLayoutWidget"))
        self.horizontalLayout_6 = QtGui.QHBoxLayout(self.horizontalLayoutWidget)
        self.horizontalLayout_6.setMargin(0)
        self.horizontalLayout_6.setObjectName(_fromUtf8("horizontalLayout_6"))
        spacerItem = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_6.addItem(spacerItem)
        self.GenerateButton = QtGui.QPushButton(self.horizontalLayoutWidget)
        self.GenerateButton.setObjectName(_fromUtf8("GenerateButton"))
        self.horizontalLayout_6.addWidget(self.GenerateButton)
        spacerItem1 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_6.addItem(spacerItem1)
        self.layoutWidget = QtGui.QWidget(self.centralwidget)
        self.layoutWidget.setGeometry(QtCore.QRect(10, 10, 641, 29))
        self.layoutWidget.setObjectName(_fromUtf8("layoutWidget"))
        self.horizontalLayout = QtGui.QHBoxLayout(self.layoutWidget)
        self.horizontalLayout.setMargin(0)
        self.horizontalLayout.setObjectName(_fromUtf8("horizontalLayout"))
        self.ToWorkLabel = QtGui.QLabel(self.layoutWidget)
        self.ToWorkLabel.setMinimumSize(QtCore.QSize(160, 0))
        self.ToWorkLabel.setMaximumSize(QtCore.QSize(200, 16777215))
        self.ToWorkLabel.setObjectName(_fromUtf8("ToWorkLabel"))
        self.horizontalLayout.addWidget(self.ToWorkLabel)
        self.ToWorkFileEdit = QtGui.QLineEdit(self.layoutWidget)
        self.ToWorkFileEdit.setObjectName(_fromUtf8("ToWorkFileEdit"))
        self.horizontalLayout.addWidget(self.ToWorkFileEdit)
        self.ToWorkButton = QtGui.QPushButton(self.layoutWidget)
        self.ToWorkButton.setMaximumSize(QtCore.QSize(30, 16777215))
        self.ToWorkButton.setObjectName(_fromUtf8("ToWorkButton"))
        self.horizontalLayout.addWidget(self.ToWorkButton)
        self.layoutWidget1 = QtGui.QWidget(self.centralwidget)
        self.layoutWidget1.setGeometry(QtCore.QRect(10, 40, 641, 29))
        self.layoutWidget1.setObjectName(_fromUtf8("layoutWidget1"))
        self.horizontalLayout_2 = QtGui.QHBoxLayout(self.layoutWidget1)
        self.horizontalLayout_2.setMargin(0)
        self.horizontalLayout_2.setObjectName(_fromUtf8("horizontalLayout_2"))
        self.FromWorkLabel = QtGui.QLabel(self.layoutWidget1)
        self.FromWorkLabel.setMinimumSize(QtCore.QSize(160, 0))
        self.FromWorkLabel.setObjectName(_fromUtf8("FromWorkLabel"))
        self.horizontalLayout_2.addWidget(self.FromWorkLabel)
        self.FromWorkFileEdit = QtGui.QLineEdit(self.layoutWidget1)
        self.FromWorkFileEdit.setObjectName(_fromUtf8("FromWorkFileEdit"))
        self.horizontalLayout_2.addWidget(self.FromWorkFileEdit)
        self.FromWorkButton = QtGui.QPushButton(self.layoutWidget1)
        self.FromWorkButton.setMaximumSize(QtCore.QSize(30, 16777215))
        self.FromWorkButton.setObjectName(_fromUtf8("FromWorkButton"))
        self.horizontalLayout_2.addWidget(self.FromWorkButton)
        self.layoutWidget2 = QtGui.QWidget(self.centralwidget)
        self.layoutWidget2.setGeometry(QtCore.QRect(10, 110, 441, 27))
        self.layoutWidget2.setObjectName(_fromUtf8("layoutWidget2"))
        self.horizontalLayout_3 = QtGui.QHBoxLayout(self.layoutWidget2)
        self.horizontalLayout_3.setMargin(0)
        self.horizontalLayout_3.setObjectName(_fromUtf8("horizontalLayout_3"))
        self.StartDateLabel = QtGui.QLabel(self.layoutWidget2)
        self.StartDateLabel.setObjectName(_fromUtf8("StartDateLabel"))
        self.horizontalLayout_3.addWidget(self.StartDateLabel)
        self.StartDateEdit = QtGui.QDateEdit(self.layoutWidget2)
        self.StartDateEdit.setDate(QtCore.QDate(2000, 1, 1))
        self.StartDateEdit.setCalendarPopup(True)
        self.StartDateEdit.setObjectName(_fromUtf8("StartDateEdit"))
        self.horizontalLayout_3.addWidget(self.StartDateEdit)
        spacerItem2 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_3.addItem(spacerItem2)
        self.EndDateLabel = QtGui.QLabel(self.layoutWidget2)
        self.EndDateLabel.setObjectName(_fromUtf8("EndDateLabel"))
        self.horizontalLayout_3.addWidget(self.EndDateLabel)
        self.EndDateEdit = QtGui.QDateEdit(self.layoutWidget2)
        self.EndDateEdit.setCalendarPopup(True)
        self.EndDateEdit.setObjectName(_fromUtf8("EndDateEdit"))
        self.horizontalLayout_3.addWidget(self.EndDateEdit)
        self.layoutWidget3 = QtGui.QWidget(self.centralwidget)
        self.layoutWidget3.setGeometry(QtCore.QRect(10, 160, 441, 23))
        self.layoutWidget3.setObjectName(_fromUtf8("layoutWidget3"))
        self.horizontalLayout_4 = QtGui.QHBoxLayout(self.layoutWidget3)
        self.horizontalLayout_4.setMargin(0)
        self.horizontalLayout_4.setObjectName(_fromUtf8("horizontalLayout_4"))
        self.RemoveDayLabel = QtGui.QLabel(self.layoutWidget3)
        self.RemoveDayLabel.setObjectName(_fromUtf8("RemoveDayLabel"))
        self.horizontalLayout_4.addWidget(self.RemoveDayLabel)
        spacerItem3 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_4.addItem(spacerItem3)
        self.RemoveWeekendsCheckBox = QtGui.QCheckBox(self.layoutWidget3)
        self.RemoveWeekendsCheckBox.setChecked(True)
        self.RemoveWeekendsCheckBox.setObjectName(_fromUtf8("RemoveWeekendsCheckBox"))
        self.horizontalLayout_4.addWidget(self.RemoveWeekendsCheckBox)
        self.layoutWidget4 = QtGui.QWidget(self.centralwidget)
        self.layoutWidget4.setGeometry(QtCore.QRect(10, 420, 641, 29))
        self.layoutWidget4.setObjectName(_fromUtf8("layoutWidget4"))
        self.horizontalLayout_5 = QtGui.QHBoxLayout(self.layoutWidget4)
        self.horizontalLayout_5.setMargin(0)
        self.horizontalLayout_5.setObjectName(_fromUtf8("horizontalLayout_5"))
        self.OutputLabel = QtGui.QLabel(self.layoutWidget4)
        self.OutputLabel.setMinimumSize(QtCore.QSize(160, 0))
        self.OutputLabel.setObjectName(_fromUtf8("OutputLabel"))
        self.horizontalLayout_5.addWidget(self.OutputLabel)
        self.OutputFileEdit = QtGui.QLineEdit(self.layoutWidget4)
        self.OutputFileEdit.setObjectName(_fromUtf8("OutputFileEdit"))
        self.horizontalLayout_5.addWidget(self.OutputFileEdit)
        self.OutputButton = QtGui.QPushButton(self.layoutWidget4)
        self.OutputButton.setMaximumSize(QtCore.QSize(30, 16777215))
        self.OutputButton.setObjectName(_fromUtf8("OutputButton"))
        self.horizontalLayout_5.addWidget(self.OutputButton)
        MainWindow.setCentralWidget(self.centralwidget)
        self.statusbar = QtGui.QStatusBar(MainWindow)
        self.statusbar.setObjectName(_fromUtf8("statusbar"))
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        MainWindow.setWindowTitle(QtGui.QApplication.translate("MainWindow", "TCXgen", None, QtGui.QApplication.UnicodeUTF8))
        self.SameTrackCheckBox.setText(QtGui.QApplication.translate("MainWindow", "Same as track to work", None, QtGui.QApplication.UnicodeUTF8))
        self.AddDayButton.setText(QtGui.QApplication.translate("MainWindow", "Add a day", None, QtGui.QApplication.UnicodeUTF8))
        self.RemoveDateEdit.setDisplayFormat(QtGui.QApplication.translate("MainWindow", "MM-dd-yyyy", None, QtGui.QApplication.UnicodeUTF8))
        self.ClearListButton.setText(QtGui.QApplication.translate("MainWindow", "Clear list", None, QtGui.QApplication.UnicodeUTF8))
        self.GenerateButton.setText(QtGui.QApplication.translate("MainWindow", "Generate", None, QtGui.QApplication.UnicodeUTF8))
        self.ToWorkLabel.setText(QtGui.QApplication.translate("MainWindow", "Track to work (.gpx):", None, QtGui.QApplication.UnicodeUTF8))
        self.ToWorkButton.setText(QtGui.QApplication.translate("MainWindow", "...", None, QtGui.QApplication.UnicodeUTF8))
        self.FromWorkLabel.setText(QtGui.QApplication.translate("MainWindow", "Track from work (.gpx):", None, QtGui.QApplication.UnicodeUTF8))
        self.FromWorkButton.setText(QtGui.QApplication.translate("MainWindow", "...", None, QtGui.QApplication.UnicodeUTF8))
        self.StartDateLabel.setText(QtGui.QApplication.translate("MainWindow", "Start date:", None, QtGui.QApplication.UnicodeUTF8))
        self.StartDateEdit.setDisplayFormat(QtGui.QApplication.translate("MainWindow", "MM-dd-yyyy", None, QtGui.QApplication.UnicodeUTF8))
        self.EndDateLabel.setText(QtGui.QApplication.translate("MainWindow", "End date:", None, QtGui.QApplication.UnicodeUTF8))
        self.EndDateEdit.setDisplayFormat(QtGui.QApplication.translate("MainWindow", "MM-dd-yyyy", None, QtGui.QApplication.UnicodeUTF8))
        self.RemoveDayLabel.setText(QtGui.QApplication.translate("MainWindow", "Day(s) to remove from the selected period:", None, QtGui.QApplication.UnicodeUTF8))
        self.RemoveWeekendsCheckBox.setText(QtGui.QApplication.translate("MainWindow", "Remove weekends", None, QtGui.QApplication.UnicodeUTF8))
        self.OutputLabel.setText(QtGui.QApplication.translate("MainWindow", "Output file name:", None, QtGui.QApplication.UnicodeUTF8))
        self.OutputButton.setText(QtGui.QApplication.translate("MainWindow", "...", None, QtGui.QApplication.UnicodeUTF8))


if __name__ == "__main__":
    import sys
    app = QtGui.QApplication(sys.argv)
    MainWindow = QtGui.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())

